{% set version = "0.17.2" %}

package:
  name: scikit-image
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/scikit-image/scikit-image-{{ version }}.tar.gz
  sha256: bd954c0588f0f7e81d9763dc95e06950e68247d540476e06cb77bcbcd8c2d8b3
  # url: https://github.com/scikit-image/scikit-image/archive/v{{ version }}.tar.gz
  # fn: scikit-image-{{ version }}.tar.gz
  # sha256: 3b8414ccb9b524d0d507909e9a4d3843af6ca9919152199d380f2b21639abf17

build:
  number: 1
  skip: true  # [py==27]
  script:
    - rm -rf skimage/viewer/tests  # we don't depend on Qt
    ########################################################
    # Remove these two lines at your own risk.
    #
    # pyproject.toml was getting detected by pip, and scikit-image was being built with modern numpy, not 1.11
    - rm -f pyproject.toml
    # I have no idea what this line actually fixes (other than speeding up the build a little bit)
    # I think windows was freaking out about path lengths, and maybe this fixed it???
    # https://github.com/conda-forge/scikit-image-feedstock/pull/39
    - {{ PYTHON }} setup.py build_ext -j2
    ########################################################
    - {{ PYTHON }} setup.py install --single-version-externally-managed --record record.txt
    # - "{{ PYTHON }} -m pip install . --disable-pip-version-check --no-deps --ignore-installed --no-cache-dir --no-build-isolation -vvv"
  entry_points:
    - skivi = skimage.scripts.skivi:main

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
  host:
    - python
    - pip
    - cython >=0.25,!=0.28.2,!=0.29.0
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=0.19
    - matplotlib-base >=2.0.0
    - networkx >=2.0
    - pillow >=4.3.0
    - pywavelets >=0.4.0
    - imageio >=2.3.0
    # scikit-image depends on dask-array
    # which requires numpy, dask-core and toolz (cytoolz for speed)
    - dask-core >=0.15.0
    - toolz >=0.7.3
    - cytoolz >=0.7.3
    # cloudpickle is necessary to provide the 'processes' scheduler for dask
    - cloudpickle >=0.2.1
    - tifffile >=2019.7.26
  run_constrained:
    - pooch >=0.5.2

test:
  requires:
    - pytest
    - pytest-localserver
  imports:
    - skimage
  commands:
    - setx MPLBACKEND "Agg"  # [win]
    - export MPLBACKEND=Agg  # [unix]
    - pytest --pyargs skimage

about:
  home: http://scikit-image.org/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Image processing in Python.
  description: |
    scikit-image is a collection of algorithms for image processing. 
    It is available free of charge and free of restriction. 
    We pride ourselves on high-quality, peer-reviewed code, 
    written by an active community of volunteers.

extra:
  recipe-maintainers:
    - jakirkham
    - jni
    - msarahan
    - ocefpaf
    - soupault
    - hmaarrfk
    - emmanuelle 
