provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}

# provider:
#   win: azure

# azure:
#   upload_packages: True
#   # I only want azure to build and upload windows
#   force: False
conda_forge_output_validation: true
